# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-04-24 15:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.CharField(max_length=255)),
                ('puuid', models.CharField(max_length=79)),
                ('level', models.PositiveSmallIntegerField()),
                ('placement', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MatchTrait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puuid', models.CharField(max_length=79)),
                ('match_id', models.CharField(max_length=255)),
                ('tier', models.PositiveSmallIntegerField()),
                ('num_units', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MatchUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puuid', models.CharField(max_length=79)),
                ('match_id', models.CharField(max_length=255)),
                ('tier', models.PositiveSmallIntegerField()),
                ('items', models.ManyToManyField(to='analyze.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Summoner',
            fields=[
                ('puuid', models.CharField(max_length=79, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('summoner_id', models.CharField(max_length=64)),
                ('account_id', models.CharField(max_length=57)),
                ('summoner_level', models.PositiveIntegerField()),
                ('tier', models.CharField(max_length=32)),
                ('rank', models.CharField(max_length=32)),
                ('league_points', models.PositiveSmallIntegerField()),
                ('wins', models.PositiveIntegerField()),
                ('losses', models.PositiveIntegerField()),
                ('top_4', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Trait',
            fields=[
                ('trait_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('bronce_min', models.PositiveSmallIntegerField(null=True)),
                ('silver_min', models.PositiveSmallIntegerField(null=True)),
                ('gold_min', models.PositiveSmallIntegerField(null=True)),
                ('chromatic_min', models.PositiveSmallIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('unit_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('rarity', models.PositiveSmallIntegerField()),
                ('trait1', models.CharField(max_length=32)),
                ('trait2', models.CharField(max_length=32)),
                ('trait3', models.CharField(blank=True, max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='matchunit',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyze.Unit'),
        ),
        migrations.AddField(
            model_name='matchtrait',
            name='trait',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyze.Trait'),
        ),
    ]
