# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-04-25 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyze', '0002_top'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchunit',
            name='unit',
            field=models.CharField(max_length=32),
        ),
    ]
