# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-04-28 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyze', '0003_auto_20200426_0002'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
    ]
