# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-06-12 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyze', '0011_auto_20200610_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyzeObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('games', models.PositiveIntegerField()),
                ('last_games', models.PositiveIntegerField()),
            ],
        ),
    ]
