# Generated by Django 2.2.12 on 2020-06-13 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyze', '0012_analyzeobject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
