# Generated by Django 2.2.12 on 2020-06-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyze', '0013_delete_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='summoner',
            name='profile_pic',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
